services:
  # DynamoDB Local
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  # Spring Boot Application
  spring-boot-app:
    build:
      context: .  # Path to your Spring Boot project directory
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Spring Boot app port
